language: generic

sudo: required

services:
  - docker

notifications:
  email: false

cache:
  directories:
    - inthezone-convex

before_install:
  -
    if [ -e "inthezone-convex/image.tar" ]; then
      docker load -i "inthezone-convex/image.tar";
    else
      docker build -t "inthezone-convex" -f Dockerfile .;
      mkdir -p "inthezone-convex"; docker save -o "inthezone-convex/image.tar" "inthezone-convex";
    fi

script:
  - docker run -v `pwd`:/build "inthezone-convex" sh -c 'make'
